package Interfaces;

/**
 *
 * @author Miguel
 */

import Util.Metodos;
import com.sun.awt.AWTUtilities;
import java.awt.Polygon;
import java.awt.Shape;
import javax.swing.ImageIcon;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        lblFondo.setIcon(new Metodos().ponerIcono("/Imagenes/login2.jpg", this.getWidth(), this.getHeight()));
        lblUserImage.setIcon(new Metodos().ponerIcono("/Imagenes/user.png"));
        lblPassImage.setIcon(new Metodos().ponerIcono("/Imagenes/locked-2.png"));
        lblImagen.setIcon(new Metodos().ponerIcono("/Imagenes/Logo2.png",lblImagen.getWidth(),lblImagen.getHeight()));
        btnIngresar.setIcon(new Metodos().ponerIcono("/Imagenes/success.png"));
        btnSalir.setIcon(new Metodos().ponerIcono("/Imagenes/error.png"));
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Icono.png")).getImage());
        this.repaint();
        //Forma del JFrame
        int[] puntos_x = {0,0,this.getWidth()/3,2*(this.getWidth()/3),this.getWidth(),this.getWidth(),2*(this.getWidth()/3)
                           ,this.getWidth()/3 };
        int[] puntos_y = {this.getHeight()/3,2*(this.getHeight()/3),this.getHeight(),this.getHeight(),2*(this.getHeight()/3),
                            this.getHeight()/3,0,0};
        Shape forma = new Polygon(puntos_x, puntos_y, 8);
        AWTUtilities.setWindowShape(this, forma); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUserImage = new javax.swing.JLabel();
        lblPassImage = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(51, 51, 51));
        lblBienvenido.setText("BIENVENIDO");
        getContentPane().add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(7, 95, 149));
        lblContraseña.setText("Contraseña:");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(7, 95, 149));
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        lblUserImage.setBackground(new java.awt.Color(0, 0, 0));
        lblUserImage.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(lblUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 30, 30));

        lblPassImage.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(lblPassImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 30, 30));

        txtUsuario.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, -1));

        txtContraseña.setText("jPasswordField1");
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, -1));

        btnIngresar.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnIngresar.setText("LOGIN");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnIngresar.setIconTextGap(12);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 40));

        btnSalir.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSalir.setIconTextGap(15);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 120, 40));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 140));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 468, 429));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Splash screenSplash = new Splash(null,false);
        dispose();
        screenSplash.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblContraseña;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPassImage;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
