/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Util.Metodos;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Miguel
 */
public class Splash extends javax.swing.JDialog {

    /**
     * Creates new form Splash
     */
    public Splash(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        lblTexto.setIcon(new Metodos().ponerIcono("/Imagenes/loading.gif", 32 , 32));
        //-------------------------   
        
        iniciarHilo1(140);
        iniciarHilo2(550);

    }

    Splash() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private synchronized void iniciarHilo1(int duracion) {
        Thread hilo = new Thread(new Runnable() {
            int x;

            @Override
            public void run() {
                try {
                    while (x <= 100) {
                        pgbProgreso.setValue(x);
                        x += 5;
                        Thread.sleep(duracion);
                    }
                    dispose();
                    Principal ventana = new Principal();
                    ventana.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        hilo.start();
    }

    private synchronized void iniciarHilo2(int duracion) {
        Thread hilo = new Thread(new Runnable() {
            int i = 0;
            String cadenas[] = {"Conectando a base de datos", "Cargando Datos de usuario", "Cargando Librerias", "Iniciando Módulos",
                "Cargando Interfaces", "Iniciando Aplicación", "OK"};

            @Override
            public void run() {
                try {
                    while (pgbProgreso.getPercentComplete()<= 1.0) {
                        i++;
                        lblTexto.setText(cadenas[i] + "...");
                        Thread.sleep(duracion);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbProgreso = new javax.swing.JProgressBar();
        lblTexto = new javax.swing.JLabel();
        lblSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(49, 11, 147, 32));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pgbProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));

        lblTexto.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Example");
        lblTexto.setIconTextGap(5);
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, -1));

        lblSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SplashScreen.png"))); // NOI18N
        lblSplash.setToolTipText("");
        getContentPane().add(lblSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Splash dialog = new Splash(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblSplash;
    private javax.swing.JLabel lblTexto;
    public javax.swing.JProgressBar pgbProgreso;
    // End of variables declaration//GEN-END:variables

}
